### ISSUE TITLE
一部が見切れてしまう問題

### ISSUE THREAD

**Issue by h-takeyeah** [su-its/ams-frontend#27]
![ams-kireteru](https://user-images.githubusercontent.com/61489178/111066600-307fa580-8503-11eb-9160-7ac602082da5.gif)

当システムはおそらくキオスクモードなりでブラウザを全画面表示にして使われることと思います．その時にスクロールしないと見切れてしまうのはよくないので修正したいです．

**Comment by ghost** [comment]
@h-takeyeah すみません、その開発時の解像度教えてください。

**Comment by h-takeyeah** [comment]
@Stroheim001 (自分でなぜこうなったか気づいたので少し恥ずかしくなっていますが書きます)

フルHDです．ただし125%に拡大して使っています←それやん

**Comment by ghost** [comment]
@h-takeyeah @equal-l2  FHDでだいたい100～125%という設計にしましょう

異議申し立ては早めにお願いします

**Comment by equal-l2** [comment]
単純にフッタの高さが高すぎるというところもあるとは思います

**Comment by h-takeyeah** [comment]
FHDで100%にして全画面表示にすればスクロールしなくて済むことが確認できました．ただ全画面表示出ない場合すこ～しだけスクロールが必要です．若干イライラします

CSS的には高さをvh(viewportのheight)から計算してきちんフィットするようにしてくれるといいんですけど，天下のBuefyだからその辺はすでにできてるんだろうなあと思います．vhで高さを定義しているネット上の色々なサンプルはそもそもスクロールバーがないのでまだ余地はあるのかなあとCSS門外漢ながら思いました．

**Comment by ghost** [comment]
@h-takeyeah なんていうか、こういう機能あったらよくね？とかは追加して、何もしないボタンだけ配置しておきますが、

そもそもどういう環境で動作させるつもりなのか？あるいはそれがスタンダードなのか、はしらないので、教えてほしいです

**Comment by h-takeyeah** [comment]
@Stroheim001 実をいうとこのブラウザからアクセスできるフロントエンドの機能はつけるつもりがなくて，モニターはいらないと先生に伝えていたので納品先の研究室でモニターがあてがわれる保証がないのです．だからどんな環境で動作することになるのか分かりません．

研究室によりますが，モニターがあてがわれるとしてHD(1280×720)以上を想定していいのではないのかなと思います．全くの勘になります．

ラズパイで動かすことになるので(セキュリティの話は置いといて)`http://<ラズパイのホスト名>/`みたいな感じでLAN内の任意のブラウザから見る形も想定されます．この場合indexページの存在意義が揺らぎますね．キオスク端末的な使い方を想定して作ってもらったのに申し訳ない．

**Comment by ghost** [comment]
@h-takeyeah (なんでそういう死ぬほど重要度が高い話が共有されてない上に、しかも勘ですみたいなぼかした感じなのか、についてはさすがに問題提起させてください)

んで、もって結局リッチなUIがいらなかった場合、APIを直接たたきにいくから、どちらかというと教授のスマホなりそういったものだけ参照可能にするべきではないでしょうか

要するにauthつけろって話ですが

後、前提条件はちゃんと喋ろうね...

**Comment by h-takeyeah** [comment]
@Stroheim001 死ぬほど重要な話を共有していなかった点はごめんなさい．authは難しいので納品までのやることリストには入れないでおきたいです

**Comment by ghost** [comment]
@h-takeyeah それじゃmilestoneにぶちこんでおいてください。

極端な言い方すると、/roomはpostされてしまうと、sql走ってしまうので不正に使おうと思えば使えてしまいます。

まさか、CUIで使うとは思ってなかったので気にしてませんでしたが...

---

えっと、せめて、/roomがpostできるのはブリッジだけにすることは可能ですか？

**Comment by h-takeyeah** [comment]
調べてみますがブリッジのリクエストのヘッダーに何か認証系のキーを持たせるか，basic認証噛ませるかくらいでいいならできると思います

**Comment by ghost** [comment]
@h-takeyeah さすがにブリッジ以外から出来るのはヤバいので対応お願いします。

**Comment by h-takeyeah** [comment]
ブリッジ以外からも叩けてしまう問題はこちらで https://github.com/su-its/ams-backend-nodejs/issues/65

**Comment by h-takeyeah** [comment]
@Stroheim001 

> んで、もって結局リッチなUIがいらなかった場合、APIを直接たたきにいくから、どちらかというと教授のスマホなりそういったものだけ参照可能にするべきではないでしょうか

UIは必要だと思います．仮になかったとしてもAPIを直接叩きに行く→だから認証が必要だという話なら，それはバックエンドのリポジトリで話し合いましょう．このフロントエンドを閲覧できる人間を制限しようというissueはまだ上がっていないですが，必要だと思うなら作っていただけますか．自分は必要だろうとは思いましたが，そこまで4月までには間に合わないだろうなと思ったのでマイルストーンに追加するにとどめてあります．よろしくお願いします．

**Comment by h-takeyeah** [comment]
本題の「見切れてしまう問題」ですが，FHD(100%)で表示件数を5件にすれば画面に入りきりました．なので表示件数を可変にするという対策は有効だったと言えます．
さらにやるならフッターを画面の下部に固定するのではなくページの下部に固定する対策ができると思います．これ以上は正直思いつかないです．

**Comment by h-takeyeah** [comment]
とりあえず`#app`の`flex-flow: column`を追加したらフッターをページの最下部に固定させることはできました．
```css
// 全ての要素がappの中にあるので、全てに適応される
#app {
  display: flex;
  flex-flow: column;
  font-family: "メイリオ", Meiryo, sans-serif;
}

// bulma からパクってきた
.has-shadow {
  box-shadow: 0 2px 3px rgba(10, 10, 10, 0.1);
}

// ヘッダに適応
.header {
  padding: 20px 10px;
}

.menu-items {
  font-size: 21px;
}

// ヘッダとメインコンテンツに適応されてます
.main-content {
  flex: 1;
  overflow-y: visible;
  position: relative;
  z-index: 10;
  // margin-bottom: 168px;
}

// buefyのCSSでは厳しかったので、!importantで無理にやってます
.footer {
  // position: fixed;
  width: 100%;
  bottom: 0;
  height:168px;
}

```

[z-index](https://developer.mozilla.org/ja/docs/Web/CSS/z-index)も消してよさげですかね～

**Comment by equal-l2** [comment]
footerの情報がめちゃくちゃ少ないので、フッタのheightももう少し減らしてスリムにしても良さそうですね

**Comment by h-takeyeah** [comment]
色々試してみました．最低限これでもよさそうです．`min-height: 100vh;`を追加しました．これはaboutのページで内容が少ないことによってフッターがページの真ん中あたりに上がってきてしまうのを防止するためです．あとはbulmaのデフォルトでそれなりの見た目になるので特にいじっていません．

```css
// 全ての要素がappの中にあるので、全てに適応される
#app {
  display: flex;
  flex-flow: column;
  font-family: "メイリオ", Meiryo, sans-serif;
  min-height: 100vh;
}

// bulma からパクってきた
.has-shadow {
  box-shadow: 0 2px 3px rgba(10, 10, 10, 0.1);
}

// ヘッダに適応
.header {
  padding: 20px 10px;
}

.menu-items {
  font-size: 21px;
}

// ヘッダとメインコンテンツに適応されてます
.main-content {
  flex: 1;
}

.footer {
  // 何もなし
}
```
